### ISSUE TITLE
Build fails in test stage

### ISSUE THREAD

**Issue by gautamjeyaraman** [Graphify/graphify#22]
Here is the log:

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.neo4j.nlp:graphify:jar:1.0.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 189, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] graphify
[INFO] myproject
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building myproject 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> maven-assembly-plugin:2.2-beta-5:assembly (default-cli) @ graphify >>>
[INFO]                                                                         
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] Forking graphify 1.0.0
[INFO] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ graphify ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/mohan/graphify-master/src/extension/src/main/resources
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:compile (scala-compile-first) @ graphify ---
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.10.4
[WARNING]  org.neo4j:neo4j-cypher:2.2.1 requires scala version: 2.10.5
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ graphify ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ graphify ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/mohan/graphify-master/src/extension/src/test/resources
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:testCompile (scala-test-compile) @ graphify ---
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.10.4
[WARNING]  org.neo4j:neo4j-cypher:2.2.1 requires scala version: 2.10.5
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ graphify ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ graphify ---
[INFO] Surefire report directory: /home/mohan/graphify-master/src/extension/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.neo4j.nlp.impl.util.GraphManagerTest
{0} is known {1}
[{"label":"document","rating":4.1},{"label":"ensemble","rating":2.6},{"label":"sentence","rating":2.6},{"label":"paragraph","rating":2.6}]
[{"label":"ensemble","rating":4.500000000000001},{"label":"sentence","rating":4.500000000000001},{"label":"paragraph","rating":4.500000000000001},{"label":"document","rating":4.5}]
[{"label":"paragraph","rating":7.000000000000001},{"label":"ensemble","rating":5.500000000000001},{"label":"document","rating":5.500000000000001},{"label":"sentence","rating":5.500000000000001}]
FEATURE VECTOR for 'The last word in a sentence is interesting'
[0.21052631578947367, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.05263157894736842, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
COSINE SIMILARITY
0.7419354838709676
COSINE SIMILARITY for v1 and v3
0.7419354838709676
COSINE SIMILARITY for v1 and v4
0.7332355751067664
{"classes":[{"class":"paragraph","similarity":0.7201690119262738},{"class":"sentence","similarity":0.19104118698371517},{"class":"ensemble","similarity":0.180837591224175}]}
{"classes":[{"class":"paragraph","similarity":0.7201690119262738},{"class":"sentence","similarity":0.19104118698371517},{"class":"ensemble","similarity":0.180837591224175}]}
[{"feature":"{0} {1}","frequency":4,"variance":0.08652870591125471,"affinity":0.027027027027026983},{"feature":"{0} in {1}","frequency":1,"variance":0.08652870591125471,"affinity":0.027027027027026983},{"feature":"{0} a {1}","frequency":1,"variance":0.08652870591125471,"affinity":0.027027027027026983},{"feature":"{0} in a sentence {1}","frequency":1,"variance":0.30932024237944566,"affinity":0.027027027027026983},{"feature":"{0} sentence {1}","frequency":1,"variance":0.1398492871960801,"affinity":0.027027027027026983},{"feature":"{0} sentence is {1}","frequency":1,"variance":0.30932024237944566,"affinity":0.027027027027026983},{"feature":"{0} word in a {1}","frequency":1,"variance":0.0817755635771097,"affinity":0.027027027027026983},{"feature":"{0} word {1}","frequency":1,"variance":0.07969562544474496,"affinity":0.027027027027026983},{"feature":"{0} in a {1}","frequency":1,"variance":0.08652870591125471,"affinity":0.027027027027026983},{"feature":"{0} word in a sentence is {1}","frequency":1,"variance":0.30932024237944566,"affinity":0.027027027027026983},{"feature":"{0} word in a sentence {1}","frequency":1,"variance":0.30932024237944566,"affinity":0.027027027027026983},{"feature":"{0} a sentence {1}","frequency":1,"variance":0.1398492871960801,"affinity":0.027027027027026983},{"feature":"{0} in a sentence is {1}","frequency":1,"variance":0.30932024237944566,"affinity":0.027027027027026983},{"feature":"{0} word in {1}","frequency":1,"variance":0.0817755635771097,"affinity":0.027027027027026983},{"feature":"{0} is {1}","frequency":1,"variance":0.08652870591125471,"affinity":0.027027027027026983},{"feature":"{0} a sentence is {1}","frequency":1,"variance":0.30932024237944566,"affinity":0.027027027027026983},{"feature":"{0} a ensemble {1}","frequency":0,"variance":0.21114206209178935,"affinity":0.027027027027026983},{"feature":"{0} word in a paragraph is {1}","frequency":0,"variance":1.0,"affinity":0.027027027027026983},{"feature":"{0} in a document {1}","frequency":0,"variance":0.1414213562373095,"affinity":0.027027027027026983},{"feature":"{0} note in a ensemble {1}","frequency":0,"variance":0.40551750201988135,"affinity":0.027027027027026983},{"feature":"{0} note in a ensemble is {1}","frequency":0,"variance":0.40551750201988135,"affinity":0.027027027027026983},{"feature":"{0} a paragraph is {1}","frequency":0,"variance":1.0,"affinity":0.027027027027026983},{"feature":"{0} in a ensemble {1}","frequency":0,"variance":0.3344847472398428,"affinity":0.027027027027026983},{"feature":"{0} in a paragraph {1}","frequency":0,"variance":0.1384187178777149,"affinity":0.027027027027026983},{"feature":"{0} a ensemble is {1}","frequency":0,"variance":0.3344847472398428,"affinity":0.027027027027026983},{"feature":"{0} word in a document {1}","frequency":0,"variance":0.1414213562373095,"affinity":0.027027027027026983},{"feature":"{0} in a paragraph is {1}","frequency":0,"variance":1.0,"affinity":0.027027027027026983},{"feature":"{0} a paragraph {1}","frequency":0,"variance":0.09701703390049769,"affinity":0.027027027027026983},{"feature":"{0} a document {1}","frequency":0,"variance":0.1414213562373095,"affinity":0.027027027027026983},{"feature":"{0} paragraph {1}","frequency":0,"variance":0.09701703390049769,"affinity":0.027027027027026983},{"feature":"{0} ensemble is {1}","frequency":0,"variance":0.21114206209178935,"affinity":0.027027027027026983},{"feature":"{0} ensemble {1}","frequency":0,"variance":0.14304481760810453,"affinity":0.027027027027026983},{"feature":"{0} word in a paragraph {1}","frequency":0,"variance":0.1384187178777149,"affinity":0.027027027027026983},{"feature":"{0} paragraph is {1}","frequency":0,"variance":0.1384187178777149,"affinity":0.027027027027026983},{"feature":"{0} document is {1}","frequency":0,"variance":0.1414213562373095,"affinity":0.027027027027026983},{"feature":"{0} in a ensemble is {1}","frequency":0,"variance":0.40551750201988135,"affinity":0.027027027027026983},{"feature":"{0} document {1}","frequency":0,"variance":0.0823030195043518,"affinity":0.027027027027026983}]
[{feature={0} paragraph is interesting {1}, affinity=0.5263157894736842}, {feature={0} word in a paragraph is {1}, affinity=0.5263157894736842}, {feature={0} a paragraph is {1}, affinity=0.5263157894736842}, {feature={0} in a paragraph is {1}, affinity=0.5263157894736842}, {feature={0} in a ensemble is {1}, affinity=0.22907454048362486}, {feature={0} note in a ensemble is {1}, affinity=0.22907454048362486}, {feature={0} note in a ensemble {1}, affinity=0.22907454048362486}, {feature={0} a ensemble is {1}, affinity=0.19355816309360557}, {feature={0} in a ensemble {1}, affinity=0.19355816309360557}, {feature={0} a sentence is {1}, affinity=0.180975910663407}, {feature={0} in a sentence is {1}, affinity=0.180975910663407}, {feature={0} word in a sentence {1}, affinity=0.180975910663407}, {feature={0} word in a sentence is {1}, affinity=0.180975910663407}, {feature={0} sentence is {1}, affinity=0.180975910663407}, {feature={0} in a sentence {1}, affinity=0.180975910663407}, {feature={0} interesting {1}, affinity=0.1441669196714421}, {feature={0} ensemble is {1}, affinity=0.13188682051957887}, {feature={0} a ensemble {1}, affinity=0.13188682051957887}, {feature={0} is interesting {1}, affinity=0.10964912280701752}]
[{feature={0} document is interesting {1}, affinity=0.5555555555555556}, {feature={0} a document is {1}, affinity=0.5555555555555556}, {feature={0} word in a document is {1}, affinity=0.5555555555555556}, {feature={0} in a document is {1}, affinity=0.5555555555555556}, {feature={0} the {1}, affinity=0.5555555555555556}, {feature={0} interesting {1}, affinity=0.17340668575331347}, {feature={0} ensemble is {1}, affinity=0.16112658660145024}, {feature={0} a ensemble {1}, affinity=0.16112658660145024}, {feature={0} is interesting {1}, affinity=0.1388888888888889}]
[{feature={0} word in a sentence is interesting {1}, affinity=0.5277777777777778}, {feature={0} a sentence is interesting {1}, affinity=0.5277777777777778}, {feature={0} in a sentence is interesting {1}, affinity=0.5277777777777778}, {feature={0} sentence is interesting {1}, affinity=0.5277777777777778}, {feature={0} in a ensemble is {1}, affinity=0.23053652878771846}, {feature={0} note in a ensemble is {1}, affinity=0.23053652878771846}, {feature={0} note in a ensemble {1}, affinity=0.23053652878771846}, {feature={0} a ensemble is {1}, affinity=0.19502015139769918}, {feature={0} in a ensemble {1}, affinity=0.19502015139769918}, {feature={0} word in a sentence is {1}, affinity=0.18243789896750062}, {feature={0} a sentence is {1}, affinity=0.18243789896750062}, {feature={0} in a sentence is {1}, affinity=0.18243789896750062}, {feature={0} word in a sentence {1}, affinity=0.18243789896750062}, {feature={0} sentence is {1}, affinity=0.18243789896750062}, {feature={0} in a sentence {1}, affinity=0.18243789896750062}, {feature={0} ensemble is {1}, affinity=0.13334880882367245}, {feature={0} a ensemble {1}, affinity=0.13334880882367245}, {feature={0} is interesting {1}, affinity=0.11111111111111112}]
[{feature={0} note in a ensemble is musical {1}, affinity=0.5277777777777778}, {feature={0} in a ensemble is musical {1}, affinity=0.5277777777777778}, {feature={0} a ensemble is musical {1}, affinity=0.5277777777777778}, {feature={0} ensemble is musical {1}, affinity=0.5277777777777778}, {feature={0} musical {1}, affinity=0.5277777777777778}, {feature={0} note in a ensemble is {1}, affinity=0.23053652878771846}, {feature={0} in a ensemble is {1}, affinity=0.23053652878771846}, {feature={0} note in a ensemble {1}, affinity=0.23053652878771846}, {feature={0} a ensemble is {1}, affinity=0.19502015139769918}, {feature={0} in a ensemble {1}, affinity=0.19502015139769918}, {feature={0} a sentence is {1}, affinity=0.18243789896750062}, {feature={0} in a sentence is {1}, affinity=0.18243789896750062}, {feature={0} word in a sentence {1}, affinity=0.18243789896750062}, {feature={0} word in a sentence is {1}, affinity=0.18243789896750062}, {feature={0} sentence is {1}, affinity=0.18243789896750062}, {feature={0} in a sentence {1}, affinity=0.18243789896750062}, {feature={0} ensemble is {1}, affinity=0.13334880882367245}, {feature={0} a ensemble {1}, affinity=0.13334880882367245}]
Tests run: 6, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 6.33 sec
Running org.neo4j.nlp.impl.util.VectorUtilTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.165 sec <<< FAILURE!
sentimentAnalysisTest(org.neo4j.nlp.impl.util.VectorUtilTest)  Time elapsed: 0.142 sec  <<< ERROR!
java.lang.NullPointerException
	at org.neo4j.nlp.impl.util.VectorUtilTest.readLargerTextFile(VectorUtilTest.java:240)
	at org.neo4j.nlp.impl.util.VectorUtilTest.train(VectorUtilTest.java:172)
	at org.neo4j.nlp.impl.util.VectorUtilTest.sentimentAnalysisTest(VectorUtilTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.neo4j.nlp.impl.manager.NodeManagerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.211 sec
Running org.neo4j.nlp.impl.traversal.DecisionTreeTest
{0=1, 1=1, 9=1, 2=1, 7=1, 3=1}

                                 
┌─┐   ┌─┐   ┌─┐   ┌─┐   ┌─┐   ┌─┐
│ │   │ │   │ │   │ │   │ │   │ │
│0├──>│1├──>│2├──>│3├──>│7├──>│9│
│ │   │ │   │ │   │ │   │ │   │ │
└─┘   └─┘   └─┘   └─┘   └─┘   └─┘
May 20, 2015 7:53:24 PM org.neo4j.nlp.helpers.GraphManager getOrCreateNode
INFO: Node 0 not found
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.688 sec <<< FAILURE!
testVertexPath(org.neo4j.nlp.impl.traversal.DecisionTreeTest)  Time elapsed: 0.086 sec  <<< ERROR!
org.neo4j.graphdb.TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:126)
	at org.neo4j.nlp.impl.cache.RelationshipCache.getLongs(RelationshipCache.java:46)
	at org.neo4j.nlp.impl.cache.RelationshipCache.getRelationships(RelationshipCache.java:33)
	at org.neo4j.nlp.helpers.GraphManager.getRelationships(GraphManager.java:112)
	at traversal.DecisionTree.loadBranches(DecisionTree.scala:175)
	at traversal.DecisionTree.traverseTo(DecisionTree.scala:240)
	at traversal.DecisionTree.traverseTo(DecisionTree.scala:229)
	at org.neo4j.nlp.impl.traversal.DecisionTreeTest.testVertexPath(DecisionTreeTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Transaction rolled back even if marked as successful
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:411)
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:112)
	... 36 more

Results :

Tests in error: 
  sentimentAnalysisTest(org.neo4j.nlp.impl.util.VectorUtilTest)
  testVertexPath(org.neo4j.nlp.impl.traversal.DecisionTreeTest): Transaction was marked as successful, but unable to commit transaction so rolled back.

Tests run: 11, Failures: 0, Errors: 2, Skipped: 2

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] graphify .......................................... SKIPPED
[INFO] myproject ......................................... FAILURE [ 10.342 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.716 s
[INFO] Finished at: 2015-05-20T19:53:24+05:30
[INFO] Final Memory: 17M/256M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project graphify: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/mohan/graphify-master/src/extension/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by kbastani** [comment]
Thanks for the report. I will have a look and get this resolved.

**Comment by cicero19** [comment]
Hi Kenny,

Any progress with this? I am getting the same error on the 1.0.0-M01 branch.
